name: repo-update
on:
  push:
    paths:
      - assets/repos/**
      - .github/workflows/repo-update.yml
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  repo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.ref_name }}
      - name: update repos
        run: |
          export user=ZoeyVid
          export path=assets/repos
          rm -rf $path
          mkdir -p $path
          repos=$(curl -sL "https://api.github.com/orgs/$user/repos?per_page=100" --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | jq '[ .[] | select(.archived==false and .private==false and .name != ".github") ] | sort_by(.name)')
          for repo in $(jq -r '.[].name' <<< "$repos"); do
            branch=$(jq -r --arg r "$repo" 'first(.[] | select(.name==$r).default_branch)' <<< "$repos")
            echo -e "<meta charset=\"utf-8\">\n$(curl -X POST https://api.github.com/markdown/raw --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --header "Content-Type: text/plain" -d "$(curl -sL https://raw.githubusercontent.com/$user/$repo/$branch/README.md)")\n" | tee "$path/$repo.html"
          done
          jq 'map({ (.name): { name, html_url, fork, description: (.description // ""), license: (.license.spdx_id // "") } }) | add' <<< "$repos" | tee "$path/index.json"
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@6e25e4304c75d72195ad8c6fca739cb2e99c3fb1 # v2.0.3
        with:
          pattern: "\\.json$*"
      - name: push changes
        run: |
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git add -A
          git diff-index --quiet HEAD || git commit -sm "update repos"
          git push
