name: tailwindcss-update
on:
  push:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  tailwindcss-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: update tailwindcss (minify)
        uses: ZoeyVid/tailwindcss-update@c315e0e5891d9cdc20548ac7aa455e580ce09856 # main
        with:
          input: assets/css/input.css
          output: assets/css/output.css
          params: "--minify"
      - name: update tailwindcss
        uses: ZoeyVid/tailwindcss-update@c315e0e5891d9cdc20548ac7aa455e580ce09856 # main
        with:
          input: assets/css/input.css
          output: assets/css/output.non-min.css
      - name: push changes
        run: |
          git add --force assets/css/output.css assets/css/output.non-min.css
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -sm "tailwindcss-update"
          git push
