name: tailwindcss-update
on:
  push:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
jobs:
  tailwindcss-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: run tailwindcc
        run: |
          wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64-musl -O tailwindcss
          chmod +x tailwindcss
          tailwindcss --input assets/css/input.css --output assets/css/output.css --minify
          tailwindcss --input assets/css/input.css --output assets/css/output.non-min.css "$INPUT_PARAMS"
      - name: push changes
        run: |
          git add --force assets/css/output.css assets/css/output.non-min.css
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -sm "tailwindcss-update"
          git push
