name: tailwindcss
on:
  push:
    branches:
      - develop
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  tailwindcss:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: tailwindcss
        run: |
          curl -sSfL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -o tailwindcss
          chmod +x tailwindcss
          ./tailwindcss --input assets/css/input.css --output assets/css/output.css --minify
          ./tailwindcss --input assets/css/input.css --output assets/css/output.non-min.css "$INPUT_PARAMS"
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          signoff: true
          delete-branch: true
          commit-message: tailwindcss
          branch: tailwindcss
          title: tailwindcss
          body: tailwindcss
